// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multishop.Comment.Data.Context;

#nullable disable

namespace Multishop.Comment.Migrations
{
    [DbContext(typeof(CommentMicroserviceContext))]
    partial class CommentMicroserviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Multishop.Comment.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("228654f1-5d7a-4ebd-aa80-c63ff8ec7e07"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 28, 7, 24, 56, 46, DateTimeKind.Local).AddTicks(9009));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<byte>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Comments", t =>
                        {
                            t.HasCheckConstraint("CommentEmailMinLengthConstraint", "Len(Email) >= 5");

                            t.HasCheckConstraint("CommentNameSurnameMinLengthConstraint", "Len(NameSurname) >= 5");

                            t.HasCheckConstraint("CommentRatingMaxConstraint", "Rating <= 5");

                            t.HasCheckConstraint("CommentRatingMinConstraint", "Rating >= 0");

                            t.HasCheckConstraint("CommentReviewMinLengthConstraint", "Len(Review) >= 10");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
